global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: development

# Scrape configs
scrape_configs:
  # Self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # OpenTelemetry Collector internal metrics
  - job_name: 'otel-collector-internal'
    static_configs:
      - targets: ['otel-collector:8888']

  # Application metrics from OTEL Collector
  - job_name: 'otel-collector-apps'
    static_configs:
      - targets: ['otel-collector:8889']